spring:
  application:
    name: curso-spring
    security:
      jwt:
        expiration: 3600000 # 1 hora
        secret-key: kDijZVBL6AZVhuDgorqNtI0EQWhun9oGfspAndEF7wbJq50emiHKy9velG9qjpyk
  datasource:
    url: jdbc:mysql://localhost/pruebas
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
server:
  port: 80

